# Generated by Django 3.2.16 on 2022-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='OTP'),
        ),
    ]
