# Generated by Django 3.2.16 on 2025-05-03 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_display',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Login Display'),
        ),
    ]
