# Generated by Django 4.0.2 on 2022-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
