# Generated by Django 3.2.16 on 2025-05-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0004_auto_20221202_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fb_credentails',
            options={'verbose_name': 'Facebook account Credentials'},
        ),
    ]
