# Generated by Django 3.2.16 on 2025-05-03 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scraper', '0005_alter_fb_credentails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_credentails',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fb_credentails',
            name='account_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fb_credentails',
            unique_together={('owner', 'account_number')},
        ),
    ]
